/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Storage;

import Database.DBconnection;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.products;
import net.proteanit.sql.DbUtils;
import product.home;

/**
 *
 * @author Haran
 */
public class stockDetails extends javax.swing.JFrame {
    private final Connection con;
    private PreparedStatement ps;
    private ResultSet rs;
    private Statement st;
    private boolean check_empty=false;
    private DefaultTableModel model,model2;
    private SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
    private String current_id;
    private String stock_product_id;
    private ArrayList<products> my_pr_list;
    private DefaultTableModel model1;
    private String current_stocks_pr_id_val;
    private static String get_product_name;
   
    /**
     * Creates new form stockDetails
     */
    public stockDetails() {
        
        con=DBconnection.connectDB();
        initComponents();
         Date date=new Date();
          stockdate.setMaxSelectableDate(date);
          stockdate.setMinSelectableDate(date);
        btn_cancel.setEnabled(false);
        btn_delete.setEnabled(false);
        btn_finished.setEnabled(false);
        name_error.setText("");
        count_error.setText("");
        date_error.setText("");
        combo_pname.removeAllItems();
        update_productname.setEnabled(false);
        btn_change.setEnabled(false);
        lbl_result.setText("");
        
        setCombo();
        display();
         enableFinishedButton();
         display_full_model();
    }
    private void display_full_model(){
          String sql = "SELECT * FROM stocks";
           try{
               st=con.createStatement();
               rs=st.executeQuery(sql); 
           }
           catch(SQLException e){
               JOptionPane.showMessageDialog(null, e);
           }
           finally{
               
                full_stock_view_table.setModel(DbUtils.resultSetToTableModel(rs));//show all employee details in a table
                model2=(DefaultTableModel) full_stock_view_table.getModel();//currently add
                try {
                    st.close();
                    rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
             
           }
    }
    private void set_current_stock_details(){
           model1= new DefaultTableModel(new String[]{"product_id", "product_name", "Instock"}, 0);
           String sql="select * from current_stocks";
        try {
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                model1.addRow(new Object[]{rs.getString(2),rs.getString(3),rs.getString(4)});
            }
        } catch (SQLException ex) {
            Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
               try {
                   ps.close();
                   rs.close();
               } catch (SQLException ex) {
                   Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
               }
            
        }
           
           stock_table.setModel(model1);
    }
    
  private void setCombo(){
        String sql="select  * from products where id !=ALL(select pid from stocks where check_val = ?)";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1,"0");
            rs=ps.executeQuery();
            while(rs.next()){
                combo_pname.addItem(rs.getString(2));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        finally{
            try {
                ps.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        combo_pname = new javax.swing.JComboBox<>();
        txt_count = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stock_table = new javax.swing.JTable();
        count_error = new javax.swing.JLabel();
        name_error = new javax.swing.JLabel();
        stockdate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        date_error = new javax.swing.JLabel();
        btn_delete = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        btn_finished = new javax.swing.JButton();
        btn_stockdetails = new javax.swing.JButton();
        btn_productdetails = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        full_stock_view_table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txt_productname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        update_productname = new javax.swing.JTextField();
        update_productcount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_change = new javax.swing.JButton();
        txt_current_ids = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_available_stocks = new javax.swing.JTextField();
        lbl_result = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txt_count.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_countKeyReleased(evt);
            }
        });

        btn_submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_submit.setText("Add");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Product Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Stock Count");

        stock_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        stock_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stock_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stock_table);

        count_error.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        count_error.setForeground(new java.awt.Color(255, 0, 0));
        count_error.setText("Error");

        name_error.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name_error.setForeground(new java.awt.Color(255, 0, 0));
        name_error.setText("Error");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date");

        date_error.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        date_error.setForeground(new java.awt.Color(255, 0, 0));
        date_error.setText("Error");

        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        btn_finished.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_finished.setText("Finished");
        btn_finished.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_finishedActionPerformed(evt);
            }
        });

        btn_stockdetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_stockdetails.setText("stock_details");
        btn_stockdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stockdetailsActionPerformed(evt);
            }
        });

        btn_productdetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_productdetails.setText("product_details");
        btn_productdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_productdetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(combo_pname, javax.swing.GroupLayout.Alignment.LEADING, 0, 250, Short.MAX_VALUE)
                            .addComponent(txt_count, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(count_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(213, 213, 213))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(name_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stockdate, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(date_error, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_submit)
                        .addGap(34, 34, 34)
                        .addComponent(btn_delete)
                        .addGap(33, 33, 33)
                        .addComponent(btn_cancel)
                        .addGap(43, 43, 43)
                        .addComponent(btn_stockdetails)
                        .addGap(38, 38, 38)
                        .addComponent(btn_productdetails)
                        .addGap(92, 92, 92)
                        .addComponent(btn_finished, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(combo_pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name_error)))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stockdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(date_error)
                        .addGap(5, 5, 5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(count_error))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete)
                    .addComponent(btn_cancel)
                    .addComponent(btn_submit)
                    .addComponent(btn_stockdetails)
                    .addComponent(btn_productdetails)
                    .addComponent(btn_finished))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Stock", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        full_stock_view_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        full_stock_view_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                full_stock_view_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(full_stock_view_table);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Search_product");

        txt_productname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_productnameKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("ProductName");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Count");

        btn_change.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_change.setText("Change");
        btn_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_changeActionPerformed(evt);
            }
        });

        txt_current_ids.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_current_ids.setText("Stock-Id");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Available_In_stocks");

        lbl_result.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_result.setForeground(new java.awt.Color(0, 153, 51));
        lbl_result.setText("Results");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_current_ids, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_change)
                            .addComponent(update_productcount, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                            .addComponent(update_productname)
                            .addComponent(txt_available_stocks))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_result, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_productname, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_productname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txt_current_ids))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_productname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lbl_result)))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(update_productcount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_available_stocks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btn_change)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("stock_update", jPanel2);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        btn_submit.setEnabled(true);
        btn_cancel.setEnabled(false);
        btn_delete.setEnabled(false);
       
        txt_count.setText("");
        stockdate.setDate(null);

    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        String sql="delete from stocks where id='"+current_id+"'";
        try {
            ps=con.prepareStatement(sql);
            int rowdeleted=ps.executeUpdate();

            if(rowdeleted > 0){
                JOptionPane.showMessageDialog(null,"sucessfully deleted");
            }
            else{
                JOptionPane.showMessageDialog(null,"cannot delete");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        finally{
            try {
                ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        combo_pname.removeAllItems();
        setCombo();
        display();
        txt_count.setText("");
        stockdate.setDate(null);
        display_full_model();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void stock_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stock_tableMouseClicked
        txt_count.setText(String.valueOf(model.getValueAt(stock_table.getSelectedRow(),3)));
        combo_pname.setSelectedItem(String.valueOf(model.getValueAt(stock_table.getSelectedRow(),2)));
        Date dateValue3=null;
        SimpleDateFormat date3 = new SimpleDateFormat("dd/MM/yyyy");

        try {
            dateValue3 = date3.parse(String.valueOf(model.getValueAt(stock_table.getSelectedRow(),4)));
            stockdate.setDate(dateValue3);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        btn_submit.setEnabled(false);
       
        btn_cancel.setEnabled(true);
        btn_delete.setEnabled(true);
        current_id=String.valueOf(model.getValueAt(stock_table.getSelectedRow(),0));
    }//GEN-LAST:event_stock_tableMouseClicked

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed

        boolean isCorrect= check_details();
        if(isCorrect){
            String pr_id=getProductId();
            String sql="insert into stocks(pid,product_name,available,date) values(?,?,?,?)";

            try{
                ps=con.prepareStatement(sql);
                ps.setString(1,pr_id);
                ps.setString(2,combo_pname.getSelectedItem().toString());
                ps.setDouble(3,Integer.parseInt(txt_count.getText()));
                ps.setString(4,formatter.format(stockdate.getDate()));
                ps.execute();
                JOptionPane.showMessageDialog(null, "Sucessfully Added");
            }

            catch(HeadlessException | NumberFormatException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try {
                    ps.close();
                } catch (SQLException ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            txt_count.setText("");
//            stockdate.setDate(null);
            combo_pname.removeAllItems();
            setCombo();
            display();
            enableFinishedButton();
            display_full_model();
        }

    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_countKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_countKeyReleased
        String value=txt_count.getText();
        try{
            Integer.parseInt(value);
        }
        catch(NumberFormatException e){
            txt_count.setText("");
            JOptionPane.showMessageDialog(null,"Field should include only integer numbers");
        }
    }//GEN-LAST:event_txt_countKeyReleased
    private void AddRemainingProducts(ArrayList<String> lists){
        for(String value:lists){
           String pr_id= getRemainingProductsId(value);
             String sql="insert into stocks(pid,product_name,available,date) values(?,?,?,?)";

            try{
                ps=con.prepareStatement(sql);
                ps.setString(1,pr_id);
                ps.setString(2,value);
                ps.setDouble(3,0);
                ps.setString(4,formatter.format(stockdate.getDate()));
                ps.execute();
                
            }

            catch(HeadlessException | NumberFormatException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try {
                    ps.close();
                } catch (SQLException ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }
    private ArrayList<products> update_current_product_details(){
        ArrayList<products> pr_list=new ArrayList<>();
        String sql="select * from stocks where check_val=0";
        try{
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                products pr=new products();
                pr.setProduct_id(rs.getString(2));
                pr.setProduct_name(rs.getString(3));
                pr.setCount(rs.getString(4));
                
                pr_list.add(pr);
            }
        }
        catch(Exception e){
            e.printStackTrace();
        }
        finally{
            try {
                ps.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        my_pr_list=pr_list;
        return pr_list;
    }
    private ArrayList<products> update_current_products_details(ArrayList<products> pr_list){
        ArrayList<products> new_pr_list=new ArrayList<>();
      String sql="SELECT * FROM `current_stocks` WHERE update_value=(select max(update_value) from current_stocks)";
      try{
         ps=con.prepareStatement(sql);
         rs=ps.executeQuery();
         while(rs.next()){
             for(products pr:pr_list){
                 if(rs.getString(2).equals(pr.getProduct_id())){
                     products new_pr=new products();
                     new_pr.setId(rs.getString(1));
                     new_pr.setProduct_id(rs.getString(2));
                     new_pr.setProduct_name(rs.getString(3));
                     new_pr.setCount(String.valueOf(Integer.parseInt(rs.getString(4))+Integer.parseInt(pr.getCount())));
                     new_pr_list.add(new_pr);
                 }
             }
         }
      }
      catch(Exception e){
          e.printStackTrace();
      }
      finally{
         
            try {
                 ps.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
     
       
       return new_pr_list;
    }
    private String get_update_value(){
        String value="";
        String sql="select max(update_value) from current_stocks";
        try {
            ps=con.prepareStatement(sql);
            rs=ps.executeQuery();
            while(rs.next()){
                value=rs.getString(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                ps.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
       return value; 
    }
    private void insert_current_products(ArrayList<products> pr_list){
        ArrayList<products> new_pr_list=new ArrayList<>();
         String sql2="SELECT * FROM `stocks` WHERE  pid != All(select pid from current_stocks WHERE update_value=(select max(update_value) from current_stocks)) and check_val=0";
       try{
         ps=con.prepareStatement(sql2);
         rs=ps.executeQuery();
         while(rs.next()){
             for(products pr:my_pr_list){
                 if(rs.getString(2).equals(pr.getProduct_id())){
                     products new_pr=new products();
                     new_pr.setProduct_id(rs.getString(2));
                     new_pr.setProduct_name(rs.getString(3));
                     new_pr.setCount(String.valueOf(Integer.parseInt(rs.getString(4))));
                     new_pr_list.add(new_pr);
                 }
             }
         }
      }
      catch(Exception e){
          e.printStackTrace();
      }
      finally{
         
            try {
                 ps.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
      }
       
       
          
          String update_val=get_update_value();
          if(update_val==null){
               update_val="0";
               String sql4="insert into current_stocks(pid,product_name,available,update_value) values(?,?,?,?)";
      //          JOptionPane.showMessageDialog(null, update_val);
              for(products pro:pr_list){
                      try{
                          ps=con.prepareStatement(sql4);
                          ps.setString(1,pro.getProduct_id());
                          ps.setString(2,pro.getProduct_name());
                          ps.setString(3,pro.getCount());
                          ps.setString(4,update_val);
                          ps.execute();

                      }

                      catch(HeadlessException | NumberFormatException | SQLException e){
                          JOptionPane.showMessageDialog(null, e);
                      }
                      finally{
                          try {
                              ps.close();
                          } catch (SQLException ex) {
                              Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                          }
                      }
                }
            }
            else{
                
      //          JOptionPane.showMessageDialog(null, update_val);
              for(products pro:pr_list){
                    String sql4="update  current_stocks set pid=?,product_name=?,available=?,update_value=? where id='"+pro.getId()+"'";
                      try{
                          ps=con.prepareStatement(sql4);
                          ps.setString(1,pro.getProduct_id());
                          ps.setString(2,pro.getProduct_name());
                          ps.setString(3,pro.getCount());
                          ps.setString(4,update_val);
                          ps.execute();

                      }

                      catch(HeadlessException | NumberFormatException | SQLException e){
                          JOptionPane.showMessageDialog(null, e);
                      }
                      finally{
                          try {
                              ps.close();
                          } catch (SQLException ex) {
                              Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                          }
                      }
                }
            }
          String sql="insert into current_stocks(pid,product_name,available,update_value) values(?,?,?,?)";
//          JOptionPane.showMessageDialog(null, update_val);
        for(products pro:new_pr_list){
                try{
                    ps=con.prepareStatement(sql);
                    ps.setString(1,pro.getProduct_id());
                    ps.setString(2,pro.getProduct_name());
                    ps.setString(3,pro.getCount());
                    ps.setString(4,update_val);
                    ps.execute();
                    
                }

                catch(HeadlessException | NumberFormatException | SQLException e){
                    JOptionPane.showMessageDialog(null, e);
                }
                finally{
                    try {
                        ps.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }  
    }
    private void btn_finishedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_finishedActionPerformed
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog (null, "Would You Like to Finished all details?","Warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION){
            if(stockdate.getDate()!=null){
                ArrayList<String> lists=new ArrayList<>();
                lists= setRemainingProducts();
                AddRemainingProducts(lists);
               
                insert_current_products(update_current_products_details( update_current_product_details()));
                String ch_value="0";
                String sql="update stocks set check_val=? where check_val='"+ch_value+"'";
                try{
                     ps= con.prepareStatement(sql);
                     ps.setString(1,"1");
                     int rowsAffected=ps.executeUpdate();

                     if(rowsAffected > 0){
                       JOptionPane.showMessageDialog(null,"Update sucessfully!!!");
                     }
                     else{
                         JOptionPane.showMessageDialog(null,"The work is already done!!!");
                     }
                }
                catch(HeadlessException | SQLException e){
                    Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, e);
                }
                finally{
                      try {
                          ps.close();
                      } catch (SQLException ex) {
                          Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
                      }
                }

              set_current_stock_details();
              combo_pname.removeAllItems();
              setCombo();
              enableFinishedButton();
              btn_delete.setEnabled(false);
              display_full_model();
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Date is null!!!");
            }
        }
    }//GEN-LAST:event_btn_finishedActionPerformed

    private void btn_stockdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stockdetailsActionPerformed
        set_current_stock_details();
        btn_delete.setEnabled(false);
    }//GEN-LAST:event_btn_stockdetailsActionPerformed

    private void btn_productdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_productdetailsActionPerformed
        display();
    }//GEN-LAST:event_btn_productdetailsActionPerformed

    private void txt_productnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_productnameKeyReleased
       
        try {
            String sql="select * from stocks where product_name like '"+txt_productname.getText()+"%'";
            st=con.createStatement();
            rs=st.executeQuery(sql);
          
             full_stock_view_table.setModel(DbUtils.resultSetToTableModel(rs));//show all employee details in a table
                model2=(DefaultTableModel) full_stock_view_table.getModel();//currently add
        } catch (SQLException ex) {
            Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
          try {
            String sql1="select * from stocks where product_name like '"+txt_productname.getText()+"%'";
            st=con.createStatement();
            rs=st.executeQuery(sql1);
            int size =0;
             
            if (rs != null) 
            {
              
              rs.last();    
              size = rs.getRow(); 
            }
            if(size == 0){
                 lbl_result.setForeground(Color.red);
            }
            else{
               lbl_result.setForeground(Color.GREEN); 
            }
            lbl_result.setText(String.valueOf(size)+" Results Found");
       
        } catch (SQLException ex) {
            Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_txt_productnameKeyReleased
    private void display_get_current_stock_table(){
          
        try {
            String sql="select * from stocks where product_name like '"+txt_productname.getText()+"%'";
            st=con.createStatement();
            rs=st.executeQuery(sql);
          
             full_stock_view_table.setModel(DbUtils.resultSetToTableModel(rs));//show all employee details in a table
                model2=(DefaultTableModel) full_stock_view_table.getModel();//currently add
        } catch (SQLException ex) {
            Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }
    
    private void full_stock_view_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_full_stock_view_tableMouseClicked
         btn_change.setEnabled(true);
        update_productname.setText(String.valueOf(model2.getValueAt(full_stock_view_table.getSelectedRow(),2)));
         update_productcount.setText(String.valueOf(model2.getValueAt(full_stock_view_table.getSelectedRow(),3)));
         txt_current_ids.setText(String.valueOf(model2.getValueAt(full_stock_view_table.getSelectedRow(),0)));
         stock_product_id=String.valueOf(model2.getValueAt(full_stock_view_table.getSelectedRow(),3));
         current_stocks_pr_id_val=String.valueOf(model2.getValueAt(full_stock_view_table.getSelectedRow(),1));
         set_available_stocks_details();
    }//GEN-LAST:event_full_stock_view_tableMouseClicked

    private void btn_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_changeActionPerformed
        String total;
        String sql="update stocks set available=? where id='"+txt_current_ids.getText()+"'";
        try {
            ps=con.prepareStatement(sql);
            ps.setString(1,update_productcount.getText());
            ps.executeUpdate();
           
            
        } catch (SQLException ex) {
            Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
          String sql1="update current_stocks set available=? where pid='"+current_stocks_pr_id_val+"'";
        try {
             ps=con.prepareStatement(sql1);
             ps.setString(1,String.valueOf(Integer.parseInt(txt_available_stocks.getText())+Integer.parseInt(update_productcount.getText())- Integer.parseInt(stock_product_id)));
             ps.executeUpdate();
           
        } catch (SQLException ex) {
            Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                ps.close();
            } catch (SQLException ex) {
                Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if(txt_productname.getText().isEmpty()){
             display_full_model();
        }
        else{
            display_get_current_stock_table();
        }
         
         display();
         txt_available_stocks.setText(String.valueOf(Integer.parseInt(txt_available_stocks.getText())+Integer.parseInt(update_productcount.getText())- Integer.parseInt(stock_product_id)));
        stock_product_id=update_productcount.getText();
    }//GEN-LAST:event_btn_changeActionPerformed
    private void set_available_stocks_details(){
          String sql1="select * from current_stocks  where pid=?";
        try {
            ps=con.prepareStatement(sql1);
            ps.setString(1,String.valueOf(model2.getValueAt(full_stock_view_table.getSelectedRow(),1)));
            rs=ps.executeQuery();
            while(rs.next()){
                 txt_available_stocks.setText(rs.getString(4));
            }
        } catch (SQLException ex) {
            Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        finally{
            try {
                ps.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(stockDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private ArrayList<String> setRemainingProducts(){
        ArrayList<String> lists=new ArrayList<>();
          String sql="select  * from products where id !=ALL(select pid from stocks where check_val = ?)";
        try{
            ps=con.prepareStatement(sql);
            ps.setString(1,"0");
            rs=ps.executeQuery();
            while(rs.next()){
                
                lists.add(rs.getString(2));
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        finally{
            try {
                ps.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        return lists;
    }
    private boolean check_details() {
        boolean isCorrect=true;
        if(txt_count.getText().isEmpty()){
            count_error.setText("Field is empty");
            isCorrect=false;
        }
        else{
              count_error.setText("");
        }
        if(stockdate.getDate()==null){
            date_error.setText("Date is required");
            isCorrect=false;
        }
        else{
            date_error.setText("");
            
        }
        return  isCorrect;
    }
    private String getRemainingProductsId(String name){
         String pid=null;
        String sql="select  * from products";
        try{
            st=con.createStatement();
            rs=st.executeQuery(sql);
            while(rs.next()){
               if(name.equals(rs.getString(2))){
                  pid=rs.getString(1);
               }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        finally{
            try {
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        return pid;
    }
    private String getProductId() {
        String pid=null;
        String sql="select  * from products";
        try{
            st=con.createStatement();
            rs=st.executeQuery(sql);
            while(rs.next()){
               if(combo_pname.getSelectedItem().toString().equals(rs.getString(2))){
                  pid=rs.getString(1);
               }
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        finally{
            try {
                st.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        return pid;
    }
    private void enableFinishedButton(){
         String sql = "SELECT * FROM stocks where check_val=0";
           try{
               st=con.createStatement();
               rs=st.executeQuery(sql); 
               int size =0;
                if (rs != null) 
                {
                  rs.last();    // moves cursor to the last row
                  size = rs.getRow(); // get row id 
                }
               if(size > 0){
                   btn_finished.setEnabled(true);
               }
               else{
                   btn_finished.setEnabled(false);
               }
           }
           catch(SQLException e){
               JOptionPane.showMessageDialog(null, e);
           }
           finally{
               
              
                try {
                    st.close();
                    rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
             
           }
    }
     private void display(){
           String sql = "SELECT * FROM stocks where check_val=0";
           try{
               st=con.createStatement();
               rs=st.executeQuery(sql); 
           }
           catch(SQLException e){
               JOptionPane.showMessageDialog(null, e);
           }
           finally{
               
                stock_table.setModel(DbUtils.resultSetToTableModel(rs));//show all employee details in a table
                model=(DefaultTableModel)stock_table.getModel();//currently add
                try {
                    st.close();
                    rs.close();
                } catch (SQLException ex) {
                    Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
                }
             
           }
          
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stockDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stockDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_change;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_finished;
    private javax.swing.JButton btn_productdetails;
    private javax.swing.JButton btn_stockdetails;
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> combo_pname;
    private javax.swing.JLabel count_error;
    private javax.swing.JLabel date_error;
    private javax.swing.JTable full_stock_view_table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl_result;
    private javax.swing.JLabel name_error;
    private javax.swing.JTable stock_table;
    private com.toedter.calendar.JDateChooser stockdate;
    private javax.swing.JTextField txt_available_stocks;
    private javax.swing.JTextField txt_count;
    private javax.swing.JLabel txt_current_ids;
    private javax.swing.JTextField txt_productname;
    private javax.swing.JTextField update_productcount;
    private javax.swing.JTextField update_productname;
    // End of variables declaration//GEN-END:variables

    

   
}
